### ISSUE TITLE
Add syntax highlighting to Angular elements

### ISSUE THREAD

**Issue by tyrw** [angular-ui/AngularJS-Atom#13]
It would be great if `ng-*` flags were highlighted with a different color in the HTML, that way it would be doubly-easy to scan the doc and see what's going on.

**Comment by Nokel81** [comment]
Would this help?

```
.syntax--attribute-name.syntax--html.syntax--angular {
    color: #d19a66;
}
```
I added this to my styles.less file. I know that the colour is based on my current theme but the css name should be able to be used
