### ISSUE TITLE
Overrides emmet

### ISSUE THREAD

**Issue by urecio** [angular-ui/AngularJS-Atom#19]
Hi, since I've installed this plugin, emmet tab autocompletion no longer works on HTML (Angular) files. It still works with ctrl+e.

**Comment by outsideris** [comment]
I didn't know that. I will check it.

**Comment by mplno** [comment]
I attempted a work-around with [this](https://github.com/emmetio/emmet-atom#tab-key) addition to Atom's `keymap.cson`, but still could not get the tab completion to work on the HTML (Angular) syntax.

If anyone finds a fix within the Emmet config (or patches this bug), definitely report back. I (and probably many others) love using tab completion.

**Comment by lpommers** [comment]
i'm experiencing this same issue

**Comment by petecoop** [comment]
Open keymap, add this:

```
'atom-text-editor[data-grammar="text html angular"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

**Comment by mplno** [comment]
Thanks @petecoop. That worked. I didn't have the data-grammar part right when I tried this before.

This seems like the right solution, so probably worth closing this issue.

**Comment by QuentinFchx** [comment]
I ran into the same issue, thanks for the fix.
cc @sergeche which is a contributor of the emmet plugin, just in case someone report the issue on the https://github.com/emmetio/emmet-atom repository.

**Comment by outsideris** [comment]
@QuentinFchx  :+1:
I didn't forget to close it.

**Comment by MiloFeng** [comment]
Thanks @petecoop.
