### ISSUE TITLE
use Autocomplete-plus

### ISSUE THREAD

**Issue by robertbaker** [angular-ui/AngularJS-Atom#25]

**Comment by outsideris** [comment]
I guess Autocomplete-plus use completions in this package automatically.

If we implement `provider` of autocomplete-plus, we can provide autocomplete depend on context very nicely.
But It looks like pretty complex. So, I will try to implement `provider, but it takes some time.

**Comment by ilanbiala** [comment]
+1

**Comment by ggallo** [comment]
+1

**Comment by ilanbiala** [comment]
@outsideris just to follow up, any progress on this?

**Comment by outsideris** [comment]
@ilanbiala 
I was pretty busy. I am going to try implement for supporting autocomplete-plus this month, but implementing its provider is pretty hard.

**Comment by FlappyHeart** [comment]
Hi @outsideris , any progress on this?
