### ISSUE TITLE
Provide angular semantic highlighting.

### ISSUE THREAD

**Issue by robertbaker** [angular-ui/AngularJS-Atom#26]
Currently atom does not properly highlight ```"{{scope.myvar}}"```, it highlights everything the string color.
And inside ng attributes
```
  <span ng-show="transaction.paymentAmount !=== undefined">C</span>
```
WebStorm handles angular highlighting nicely.

**Comment by outsideris** [comment]
![2015-04-19 19 42 32](https://cloud.githubusercontent.com/assets/390146/7219124/607b3a3c-e6cc-11e4-8075-4056d460d22b.png)

Now, syntax highlighting for expressions looks like above.
Did you use document type as "HTML(Angular)"

**Comment by robertbaker** [comment]
No doctype is just HTML when ng-app in body. I have partial templates with
no doctype defined.

**Comment by outsideris** [comment]
![2015-04-20 11 43 43](https://cloud.githubusercontent.com/assets/390146/7222884/91896640-e752-11e4-98dc-7db97cd4fc49.png)

I means Atom's document type, not HTML doctype. See right of bottom in above screenshot.
HTML is default for `.html`. So, this package support `HTML (Angular)`.

**Comment by KellyTeresa** [comment]
I was just trying to figure this out myself. Thanks! I didn't think to check the Atom doctype.

**Comment by outsideris** [comment]
@KellyTeresa Good!
