### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by stramel** [angular-ui/AngularJS-Atom#27]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `angularjs` package
```
Package.getStylesheetsPath (/usr/local/share/atom/resources/app.asar/src/package.js:430:9)
Package.getStylesheetPaths (/usr/local/share/atom/resources/app.asar/src/package.js:441:32)
```

Atom Version: 0.193.0-356bb7c

**Comment by outsideris** [comment]
duplicated with #21 
@stramel why did you report it again?

**Comment by stramel** [comment]
@outsideris Sorry! Did you push a new release with those changes?
