### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by stramel** [angular-ui/AngularJS-Atom#28]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/usr/local/share/atom/resources/app.asar/src/package.js:547:9)
<unknown> (/usr/local/share/atom/resources/app.asar/src/package.js:168:43)
```
Atom Version: 0.193.0-356bb7c

**Comment by outsideris** [comment]
duplicated with #22 
@stramel why did you report it again?
