### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [angular-ui/AngularJS-Atom#41]
Atom will no longer load this package after June 1st without changes. There is one deprecation on the latest version (`0.3.0`) of this package:

1. Use Workspace::onDidAddTextEditor instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by outsideris** [comment]
@benogle In my Atom(0.201), I can't see such kind of the deprecation warning and didn't understand what that mean.

But Atom show "styles/angularjs.less
Style elements within text editors using the atom-text-editor::shadow selector or the .atom-text-editor.less file extension. If you want to target overlay elements, target them directly or as descendants of atom-overlay elements." deprecation warning. 
I can't find any document about how to fix it. I just found [a issue about it](https://github.com/atom/editor-stats/issues/16).

Can you provide infomation or documents about that?

**Comment by benogle** [comment]
Super sorry about this. It was a false positive. 

You can fix the styles via this guide: https://atom.io/docs/latest/upgrading-to-1-0-apis-upgrading-your-ui-theme-or-package-selectors

**Comment by outsideris** [comment]
@benogle Thanks you for providing the guide.
So, `onDidAddTextEditor` is same warning with `atom-text-editor::shadow`?

**Comment by benogle** [comment]
No it's not the same. You can disregard the message in this thread.
