### ISSUE TITLE
Syntax highlighting is not consistent

### ISSUE THREAD

**Issue by smlombardi** [angular-ui/AngularJS-Atom#42]
Why does the new syntax hghlighting for Angular JS (especially as attributes) work in some places but not others?

See below:

![3422375190fbd762d327577c6eca67a1a657b990_690x204](https://cloud.githubusercontent.com/assets/835148/8443130/12e634c0-1f52-11e5-9000-d182f9892d98.png)

The top-most ng-click scopes as:
![45a800e2687a6d1a2801a41162c2865ab6fc90c8](https://cloud.githubusercontent.com/assets/835148/8443140/1e36c678-1f52-11e5-8019-4d2548ad2f82.png)

But the other one scopes as:
![c68fabcc104829140e76cb4ab54cca40a9d5253f](https://cloud.githubusercontent.com/assets/835148/8443147/2a30ac96-1f52-11e5-9709-55c09a6c74b7.png)

There's no reason why one works and one doesn't...

**Comment by outsideris** [comment]
That's weird. I will check it.
