### ISSUE TITLE
ng-src parses protocol relative links as comments

### ISSUE THREAD

**Issue by erickrawczyk** [angular-ui/AngularJS-Atom#43]
Found on Atom 1.0.4 with AngularJS-Atom v0.3.0 on Mac OSX 10.10.3. Replicated on another machine with same specs and install. 

When set to `HTML (Angular)` and using protocol relative links with `ng-src` (e.g. `//path/to/src` instead of `http://path/to/src`), the path is parsed incorrectly and interpreted as a comment, which flubs the rest of the file and prevents tab autocompletes. 

![image](https://cloud.githubusercontent.com/assets/10940268/9114117/2403f15c-3c26-11e5-83c2-981e1e3a9e3f.png)

Any ideas on this?

**Comment by outsideris** [comment]
I will try to debug it. Thank you for reporting.
