### ISSUE TITLE
Can't indent with tab key

### ISSUE THREAD

**Issue by offsky** [angular-ui/AngularJS-Atom#45]
When I have this package installed, I cannot use the tab key on a new line to indent.  When I disable the package I can indent again. When I run the Key Binding Resolver (command+.) I see the following:
![emmet](https://cloud.githubusercontent.com/assets/1110926/10434888/27842e84-70d1-11e5-8d1c-7925b16ca42a.png)

This started with the 0.3.2 release

**Comment by outsideris** [comment]
Thank you for reporting.
It introduced in #19 . I will check again.

**Comment by offsky** [comment]
I don't have Emmet installed, if that helps

**Comment by outsideris** [comment]
@offsky It's good infomation.

**Comment by herrherrmann** [comment]
Same goes for me. No Emmet installed, can't use tab anymore with angularjs package activated.

**Comment by SHDavies** [comment]
I also have the same problem. It only seems to happen on HTML(Angular) files. JS files seem to work fine.

**Comment by outsideris** [comment]
I rollback it in @4012a0d . It was my fault.
Please check it again in v0.3.3.

**Comment by herrherrmann** [comment]
Thanks, working again now with 0.3.3. :+1:

**Comment by outsideris** [comment]
@herrherrmann Thank you for feedback.
