### ISSUE TITLE
Regarding div element generating a class attribute

### ISSUE THREAD

**Issue by henns20** [angular-ui/AngularJS-Atom#49]
Question:  When generating Div element it automatically generates a class attribute.  Is this  angular ui package doing this? If so is there a way I can modified so it does not generate a class attribute?

Started using angular ui package.

 Notice when I started using it.  When generating Div element it automatically generates a class attribute. 
 I looked through the code but couldn't figure out for sure. 

Goal: - so my overall goal is to only have a class when I use the emmet convention of div.classname  to generate a class.

Just a quick other note: 
I use the emmet package as well - ( I remapped the tab key in that package to ="unset!"  and use the ctrl-e to work with  emmet) 

thanks

**Comment by outsideris** [comment]
@henns20 How did you generate div element?

**Comment by henns20** [comment]
Used the tab key.
Nevermind sorry - I just disabled it and tried it again and seems to be  an
emmet property.

 There is something conflicting in my set up [unset  tab  with emmet, etc],
but at this point really the answer to my question is that the source of
the dividend class a your is not from this project seemingly to me.

 sorry thanks

**Comment by henns20** [comment]
Update: language-html package was the issue

conflict was with language-html package

That was the 1 those creating the tag  that I was having the issue with

**Comment by outsideris** [comment]
@henns20 I saw your feedback too lately. Thank you for your feedback.
