### ISSUE TITLE
ng-model-options not colored correctly

### ISSUE THREAD

**Issue by livelazily** [angular-ui/AngularJS-Atom#58]
The `-options` part not colored

![screen shot 2016-02-22 at 16 03 49](https://cloud.githubusercontent.com/assets/449935/13212666/e805c5e0-d97d-11e5-87d8-82ff42dfadc4.png)

**Comment by prezmo** [comment]
There's a little bug in regexp string in file grammars/angularjs.cson in the package. You can easily correct it yourself :). Replace line line 147 with:
`'messages|message|model-options|model|mousedown|mouseenter|mouseleave|mousemove|mouseover|mouseup|' +`
Similar problem with switch-when and switch-default in line 152 you can replace it with: `'selected|show|src|srcset|style|strict-di|submit|switch-when|switch-default|switch|' +`

**Comment by Gabrielmtn** [comment]
awesome fix! I added it, would recommend for a PR
