### ISSUE TITLE
How to Enable in .html.haml

### ISSUE THREAD

**Issue by kuroshhashemi** [angular-ui/AngularJS-Atom#86]
Hi, pardon if this is an obvious question but I'm still new to coding.  Why isn't AngularJS-Atom working in my .html.haml project files?  Thanks

**Comment by outsideris** [comment]
Because it supports HTML nows. See [here](https://github.com/angular-ui/AngularJS-Atom/blob/ec722417fa6c4bd8b18fdc7a04b4fb30f14064b7/grammars/angularjs.cson#L11).
It should add new grammar to support HAML.
